### ISSUE TITLE
Have a height scroll issue with cp-react-table 

### ISSUE THREAD

**Issue by shrutimalkood** [constantin-p/cp-react-tree-table#24]
I am unable to get the proper height with all rows without scroll.

On expand of 1 row few rows at the end are hidden.

**Comment by MartinJesu** [comment]
I am also facing same kind of issue

**Comment by constantin-p** [comment]
> I am also facing same kind of issue

Hi @MartinJesu,

Can you confirm being able to reproduce this issue with the latest version of the library [`v1.0.0-beta.9`](https://www.npmjs.com/package/cp-react-tree-table/v/1.0.0-beta.9)? If so, it would be great if you could share an example on [__JSFiddle__](http://jsfiddle.net), that can be used to reproduce the issue.

**Comment by zoness32** [comment]
I can confirm this is an issue in the latest version. Kinda breaks the whole thing.

![image](https://user-images.githubusercontent.com/2281616/84433951-f8e67480-abe3-11ea-8ea1-a1cbc708dfe5.png)

**Comment by zoness32** [comment]
After forking the repo and digging into the code for a couple days, I realized that the issues I've been having were due to CSS styles I was applying in my own app. As far as I can tell there is no issue with this library. In my case I was trying to manipulate row heights to make other aspects of the row fit. The proper way to influence row height is to add a "height" property to the objects in your data array.
